### ISSUE TITLE
when function will not receive options

### ISSUE THREAD

**Issue by PhilippSoehnlein** [artefact-group/yeoman-option-or-prompt#6] opened 2016-01-11 16:18 UTC
If a prompt has a `when`-option, the callback is called, but the first param is always an empty object (instead of the already given answers).

Here's an example code that brings up the second question if the first one is answered with `a` on prompt. But if it's given as option (`yo some-generator --q1 a`), the second question will not come up, because the first param of the when function is just an empty object:

``` javascript
var yeoman = require('yeoman-generator');
var optionOrPrompt = require('yeoman-option-or-prompt');

module.exports = yeoman.Base.extend( {
     _optionOrPrompt: optionOrPrompt,

     prompting: function () {
         var done = this.async();
         this._optionOrPrompt(
             [
                 {
                       type:    'input',
                       name:    'q1',
                       message: 'Question 1',
                 },
                 {
                     type:    'input',
                     name:    'q2',
                     message: 'Question 2',
                     when:    function( alreadyGivenAnswers ) {
                         console.log(alreadyGivenAnswers);
                         return alreadyGivenAnswers.q1 === 'a';
                     }
                 },
             ],
             function ( answers ) {
                 this.log( answers );
                 done();
            }.bind( this )
         );
     }
} );
```

I already digged into the code, but am afraid, that it's not possible to solve this. I hope someone can prove me wrong.

**Comment by PhilippSoehnlein** [comment] 2016-01-12 08:43
I rethought it and think the provided PR fixes the issue.

**Comment by funwhilelost** [comment] 2017-01-23 17:49
Closing this as a duplicate of #5.  I'll look through the PRs today.

**Closed as completed by funwhilelost** 2017-01-23 17:49 UTC
